spring:
  application:
    name: multids
  threads:
    virtual:
      enabled: true
  retry:
    initial-interval: 200
    max-interval: 5000
    multiplier: 3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    rw:
      driver-class-name: com.yugabyte.Driver
      url: jdbc:yugabytedb://127.0.0.2:5433/yugabyte?load-balance=true&topology-keys=ybcloud.ap-south-1.ap-south-1c
      username: yugabyte
      password: yugabyte
      hikari:
        pool-name: rw-pool
        minimum-idle: 3
        maximum-pool-size: 3
        auto-commit: false
        keepalive-time: 120000
        connection-init-sql: "prepare warmup as SELECT 1; execute warmup; commit;"
        connection-timeout: 15000
        data-source-properties:
          ApplicationName: multids-rw
          socketTimeout: 15
          yb-servers-refresh-interval: 180
          loginTimeout: 10
          connectTimeout: 5
    ro:
      driver-class-name: com.yugabyte.Driver
      url: jdbc:yugabytedb://127.0.0.2:5433/yugabyte?load-balance=true&topology-keys=ybcloud.ap-south-1.ap-south-1b
      username: yugabyte
      password: yugabyte
      hikari:
        pool-name: ro-pool
        minimum-idle: 6
        maximum-pool-size: 6
        auto-commit: false
        keepalive-time: 120000
        connection-init-sql: "set default_transaction_read_only=on; set yb_read_from_followers=on; prepare warmup as SELECT 1; execute warmup; commit;"
        connection-timeout: 15000
        data-source-properties:
          ApplicationName: multids-ro
          socketTimeout: 15
          yb-servers-refresh-interval: 180
          loginTimeout: 10
          connectTimeout: 5
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.yugabyte.Driver: TRACE
#    org.springframework.jdbc.datasource: DEBUG
#    org.springframework.transaction: TRACE

