spring:
  application:
    name: yb-spring-boot-app
  threads:
    virtual:
      enabled: true
  retry:
    initial-interval: 200
    max-interval: 5000
    multiplier: 2
    max-attempts: 3
    jitter: 0.2

  r2dbc:
    name: yb-r2dbc-app
    url: r2dbc:postgresql://127.0.0.2:5433/yugabyte?loadBalance=true&topologyKeys=ybcloud.ap-south-1.ap-south-1c
    username: yugabyte
    password: yugabyte
    pool:
      initial-size: 3
      max-size: 3
      max-idle-time: 2m
      validation-query: SELECT 1
      max-acquire-time: 15s
    properties:
      applicationName: yb-r2dbc-app
      tcpKeepAlive: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.yugabyte.Driver: TRACE
#    org.springframework.jdbc.datasource: DEBUG
#    org.springframework.transaction: TRACE

